[package]
name = "grootings"
version = "0.1.0"
authors = ["Geo <george.crist5@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
